on: workflow_dispatch

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v3
      - id: foo
        uses: haertale/hello-world-composite-action@v3
        with:
          who-to-greet: 'Alexander the Great'
      - run: echo random-number ${{ steps.foo.outputs.random-number }}
        shell: bash
