on: workflow_dispatch

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v3
      - run: mkdir -p path/to/some && touch path/to/some/file.txt && echo "Some text here." >> path/to/some/file.txt
        shell: bash
      - id: foo
        uses: haertale/hello-world-composite-action@v6
        with:
          who-to-greet: 'Alexander the Great'
          some-file: path/to/some/file.txt
      - run: echo random-number ${{ steps.foo.outputs.random-number }}
        shell: bash
